INSERT INTO passwords (id, website_url, website_username, website_password,user_id, category_id, organization_id) VALUES
(17,'https://www.youtube.com/', 'github@youtube.com','password',1,3,1 ),
(2,'https://www.facebook.com/', 'github@facebook.com','password',1,1,1 ),
(3,'https://www.linkedin.com/', 'github@linkedin.com','password',1,2,1 ),
(4,'https://www.twitter.com/', 'github@twitter.com','password',1,3,1 ),
(5,'https://www.reddit.com/', 'github@reddit.com','password',1,3,1 ),
(6,'https://www.tdcanadatrust.com/', 'github@td.com','password',1,2,1 ),
(7,'https://www.staples.ca/', 'github@staples.ca','password',1,2,1),
(8,'https://wealthsimple.com/', 'github@wealthsimple.com','password',1,3,1),
(9,'https://www.youtube.com/', 'github@youtube.com','password',2,3,1 ),
(10,'https://www.facebook.com/', 'github@facebook.com','password',2,1,1 ),
(11,'https://www.linkedin.com/', 'github@linkedin.com','password',2,2,1 ),
(12,'https://www.twitter.com/', 'github@twitter.com','password',2,3,1 ),
(13,'https://www.reddit.com/', 'github@reddit.com','password',2,3,1 ),
(14,'https://www.tdcanadatrust.com/', 'github@td.com','password',2,2,1 ),
(15,'https://www.staples.ca/', 'github@staples.ca','password',2,2,1),
(16,'https://wealthsimple.com/', 'github@wealthsimple.com','password',2,3,1);
